export {
  BADGE_HEIGHT,
  SECOND_BADGE_LEFT,
  FIRST_BADGE_LEFT,
  FIRST_BADGE_TOP,
  SECOND_BADGE_TOP,
  SECTION_2_FIRST_BADGE_LEFT,
  SECTION_2_FIRST_BADGE_TOP,
  BADGES_CONTAINER_WIDTH,
  BADGES_CONTAINER_HEIGHT,
} from './badgeLayout';
